pipeline {
    agent any

    environment {
        APP_NAME = "cicd-flask-app"
    }

    stages {
        stage('Checkout Latest Code') {
            steps {
                checkout scm
            }
        }

        // stage('Run Tests') {
        //     steps {
        //         sh '''
        //         python3 -m venv venv
        //         . venv/bin/activate
        //         pip install -r requirements.txt
        //         pytest tests/
        //         '''
        //     }
        // }

        stage('Build Docker Image') {
            steps {
                sh '''
                cd Devops-Ci-cd/PROJECT
                docker build -t $APP_NAME:latest .
                '''
            }
        }

        stage('Deploy Application') {
            steps {
                sh '''
                cd Devops-Ci-cd/PROJECT
*               docker compose up -d --build
                docker ps
                '''
            }
        }
    }

    post {
        success {
            echo "Deployment successful."
        }
        failure {
            echo "Deployment failed."
        }
    }
}